#! /bin/sh

#Keyboard stuff
sxhkd &
~/.qa/set-keeb.sh &

# Bar 
polybar &

# Wallpaper and compositor
picom &
feh --bg-scale '/home/skate/Pictures/wallpapers/anime-t5.jpg'   
#GUI apps
# solaar &
# discord &
blueberry-tray &


#Workspaces
bspc monitor -d I II III IV V

#Borders,gaps
bspc config border_width         5 
bspc config window_gap           10
bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config top_padding 	 15
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#Border colors
bspc config normal_border_color "#42483e"
bspc config focused_border_color "#b9b6bd"


